# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=1000)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='User.Person')),
            ],
        ),
    ]
